QALI-63: Support HTTP basic authentication
qalipsis/qalipsis-plugin-netty pull request #21
Opened 2024-06-25 08:17 UTC by oceenachi

2024-06-25 20:06 UTC, ericjesse requested changes

2024-07-01 08:53 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/HttpRequestBuilder.kt
> +internal interface HttpRequestBuilder : RequestBuilder<HttpRequest<*>> {
do not make it internal, otherwise, how can the scenario developer use it in their own scenarios?

2024-07-01 08:54 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/request/AbstractHttpRequest.kt
> +import java.nio.charset.StandardCharsets
Are those imports really used?

2024-07-01 08:55 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/request/HttpRequest.kt
> +        private fun encodeToBase64(credentials: String) =
I did not mean to make the function here. What is the benefit?
We just want to save the creation of the base64 encoder instance each time we use it.
`Base64.getEncoder()`

2024-07-01 08:56 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/spec/HttpClientStepSpecification.kt
> +internal interface HttpClientStepSpecification<INPUT, OUTPUT> :
If you set specifications internal, nobody will be able to use them an any scenario...

2024-07-01 08:56 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/request/SimpleHttpRequest.kt
> +internal data class SimpleHttpRequest constructor(
If you set specifications internal, nobody will be able to use them an any scenario...

2024-07-01 08:57 UTC, ericjesse commented on netty/src/test/kotlin/io/qalipsis/plugins/netty/http/client/Http1ClientIntegrationTest.kt
> +    @Timeout(TIMEOUT_SECONDS)
Ok. But why did you only write that test for the HTTP 1 and not for HTTP 2 tests?

2024-07-01 08:58 UTC, ericjesse commented on netty/src/test/kotlin/io/qalipsis/plugins/netty/http/spec/HttpClientStepSpecificationImplTest.kt
> +    internal fun `should add the right http headers to the step specification`() {
Nice test, thank you.

2024-07-01 10:25 UTC, oceenachi commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/HttpRequestBuilder.kt
> +internal interface HttpRequestBuilder : RequestBuilder<HttpRequest<*>> {
This was done because of the after-effects of making SimpleHttpRequest internal. The functions in HttpRequestBuilder don't compile anymore. It has this error `'public' function exposes its 'internal' return type SimpleHttpRequest`. I guess we might have to revert to making `SimpleHttpRequest` public.

2024-07-01 11:10 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/HttpRequestBuilder.kt
> +internal interface HttpRequestBuilder : RequestBuilder<HttpRequest<*>> {
All the functions and types that are directly involved in the step specifications should be public.

2024-07-01 14:17 UTC, oceenachi commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/HttpRequestBuilder.kt
> +internal interface HttpRequestBuilder : RequestBuilder<HttpRequest<*>> {
Ohh  you said to make the constructor internal

2024-07-01 14:26 UTC, oceenachi commented on netty/src/test/kotlin/io/qalipsis/plugins/netty/http/spec/HttpClientStepSpecificationImplTest.kt
> +    internal fun `should add the right http headers to the step specification`() {
I am not sure I tested anything here though.

2024-07-01 19:50 UTC, ericjesse approved these changes
There are 2 comments to fix before you merge.

2024-07-01 19:50 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/request/HttpRequest.kt
> +    companion object {
make the companion private.

2024-07-01 19:50 UTC, ericjesse commented on netty/src/main/kotlin/io/qalipsis/plugins/netty/http/request/SimpleHttpRequest.kt
> +data class SimpleHttpRequest internal constructor(
You can also make the constructor of the FormOrMultiPartRequest internal, that's a very good idea.

2024-07-02 09:50 UTC, merged